name: Trigger openshift-ci automation
on:
  create
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Test
        run: |
          export BRANCH=${{ github.event.ref }}
          echo $BRANCH
          # check if version starts with v or not
          if [[ BRANCH[0] == v ]];then      
            curl -X POST https://api.github.com/repos/kamuserbot/release/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.ACTIONS_KEY }} --data '{"event_type": "Trigger Workflow", "client_payload": { "branch", "$BRANCH" }}'
            echo "Request sent!"
          else 
            echo "skipping Workflow activation"