name: workflow_01
on:
  create
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          echo ${{ github.event }}
          echo "curl -X POST https://api.github.com/repos/:userName/:repoName/dispatches -H 'Accept: application/vnd.github.everest-preview+json' -u ${{ secrets.ACTIONS_KEY }} --data '{"event_type": "Trigger Workflow", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'"
      - uses: actions/checkout@v3
